import { useState } from 'react';

export default function PostActions({ postId, initialVotes, initialBoosts, voted = false, canVote = true, canBoost = false, body }: { postId: string; initialVotes: number; initialBoosts: number; voted?: boolean; canVote?: boolean; canBoost?: boolean; body: string }) {
  const [votes, setVotes] = useState(initialVotes); const [boosts, setBoosts] = useState(initialBoosts); const [didVote, setDidVote] = useState(voted); const [busy, setBusy] = useState(false);
  async function vote() { if (!canVote || busy) return; setBusy(true); const response = await fetch(`/api/posts/${postId}/vote`, { method: 'POST' }); const data = await response.json() as { voted?: boolean; error?: string }; if (response.ok) { setDidVote(Boolean(data.voted)); setVotes((n) => n + (data.voted ? 1 : -1)); } else alert(data.error ?? 'Could not give a W.'); setBusy(false); }
  async function boost() { if (!canBoost || busy) return; setBusy(true); const response = await fetch('/api/checkout/boost', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ postId }) }); const data = await response.json().catch(() => ({})) as { redirect?: string; error?: string }; if (response.redirected) location.href = response.url; else if (data.redirect) { setBoosts((n) => n + 1); location.href = data.redirect; } else if (!response.ok) alert(data.error ?? 'Could not start checkout.'); setBusy(false); }
  function share() { const text = `${body} — RETARDMAX`; const url = `${location.origin}/p/${postId}`; void fetch('/api/analytics', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ event: 'share_clicked', properties: { post_id: postId } }) }); window.open(`https://x.com/intent/post?text=${encodeURIComponent(`${text}\n${url}`)}`, '_blank', 'noopener,noreferrer'); }
  return <div className="flex flex-wrap items-center gap-2 text-sm"><button className={`inline-flex items-center gap-1.5 rounded-lg border px-3.5 py-1.5 font-black uppercase tracking-wide transition enabled:hover:-translate-y-0.5 disabled:cursor-not-allowed ${didVote ? 'border-flame bg-flame text-white shadow-lg shadow-flame/25' : 'border-white/15 bg-white/5 text-white/75 enabled:hover:border-flame/60 enabled:hover:text-white'}`} onClick={vote} disabled={!canVote || busy} aria-pressed={didVote} title={didVote ? 'Take back your W' : 'Give this a W'}>W <span className="tabular-nums">{votes}</span></button><button className="inline-flex items-center gap-1.5 rounded-lg border border-white/15 bg-white/5 px-3.5 py-1.5 font-black uppercase tracking-wide text-white/75 transition enabled:hover:-translate-y-0.5 enabled:hover:border-flame/60 enabled:hover:text-white disabled:cursor-not-allowed" onClick={boost} disabled={!canBoost || busy} title={canBoost ? 'Boost this post for $1' : 'Boosts'}><span aria-hidden="true">⚡</span> <span className="tabular-nums">{boosts}</span>{canBoost ? <span>Boost $1</span> : null}</button><button className="inline-flex items-center gap-1.5 rounded-lg border border-white/15 bg-white/5 px-3.5 py-1.5 font-bold uppercase tracking-wide text-white/60 transition hover:-translate-y-0.5 hover:border-white/30 hover:text-white" onClick={share} title="Share to X">Share</button></div>;
}
